import numpy as np

def get_qof(y_actual, y_pred, k, mod=None):
    """
    Calculates and compiles a comprehensive set of Quality of Fit (QoF) metrics 
    for a regression model.
    
    This function attempts to extract pre-calculated metrics from a fitted model 
    object (e.g., a Statsmodels result instance) if provided. If the object is not 
    provided or lacks specific metrics, it computes them manually using NumPy.

    Args:
        y_actual (array-like): The actual/true target values.
        y_pred (array-like): The predicted values generated by the model.
        k (int): The number of predictor variables (features) used in the model.
        mod (object, optional): A fitted model object (e.g., from Statsmodels) 
                                that may contain pre-calculated metrics. Defaults to None.

    Returns:
        list: A list containing 15 QoF metrics in the following specific order:
              [R^2, Adj R^2, SST, SSE, SDE, MSE, RMSE, MAE, sMAPE, 
               Number of Observations, DF Model, DF Residuals, F-statistic, AIC, BIC]
    """
    # ==========================================
    # --- Basic Parameters ---
    # ==========================================
    # Get the number of observations (m) in the original dataset
    m = len(y_actual)  

    # ==========================================
    # --- Sum of Squares ---
    # ==========================================
    # Calculate SSE (Sum of Squared Errors)
    sse = getattr(mod, "ssr", np.sum((y_actual - y_pred)**2))

    # Calculate SST (Total Sum of Squares)
    sst = getattr(mod, "centered_tss", np.sum((y_actual - np.mean(y_actual))**2))

    # ==========================================
    # --- R-Squared Metrics ---
    # ==========================================
    # Compute R-squared (Coefficient of Determination)
    r_squared = getattr(mod, "rsquared", 1 - (sse / sst))

    # Calculate Adjusted R-squared (penalizes for adding non-useful predictors)
    adj_r_squared = getattr(mod, "rsquared_adj", 1 - (1 - r_squared) * (m - 1) / (m - k))

    # ==========================================
    # --- Error Metrics ---
    # ==========================================
    # Standard Deviation of the Errors (SDE) / Residual Standard Error
    sde = np.sqrt(getattr(mod, "mse_resid", sse / (m - k)))

    # Calculate Mean Squared Error (MSE)
    mse = getattr(mod, "mse_resid", sse / m)

    # Root Mean Squared Error (RMSE)
    rmse = np.sqrt(getattr(mod, "mse_resid", mse))

    # Mean Absolute Error (MAE)
    mae = getattr(mod, "mae", np.mean(np.abs(y_actual - y_pred)))

    # Symmetric Mean Absolute Percentage Error (sMAPE)
    smape = getattr(mod, "smape", np.mean(2 * np.abs(y_actual - y_pred) / (np.abs(y_actual) + np.abs(y_pred))) * 100)

    # ==========================================
    # --- Statistical Tests & Degrees of Freedom ---
    # ==========================================
    # Calculate F-statistic for overall model significance
    f_stat = getattr(mod, "fvalue", ((sst - sse) / k) / (sse / (m - k)))

    # Get the degrees of freedom for the model (typically equivalent to k)
    df_model = getattr(mod, "df_model", k)

    # Get the degrees of freedom for the residuals (typically m - k)
    df_resid = getattr(mod, "df_resid", m - k)

    # ==========================================
    # --- Information Criteria ---
    # ==========================================
    # Calculate Akaike Information Criterion (AIC)
    aic = getattr(mod, "aic", m * np.log(mse) + 2 * k)

    # Calculate Bayesian Information Criterion (BIC)
    bic = getattr(mod, "bic", m * np.log(mse) + k * np.log(m))

    # ==========================================
    # --- Compile Results ---
    # ==========================================
    # Initialize a list to store exactly 15 elements
    qof = list(range(15))

    qof[0]  = r_squared
    qof[1]  = adj_r_squared
    qof[2]  = sst
    qof[3]  = sse
    qof[4]  = sde
    qof[5]  = mse
    qof[6]  = rmse
    qof[7]  = mae
    qof[8]  = smape
    qof[9]  = m
    qof[10] = df_model
    qof[11] = df_resid
    qof[12] = f_stat
    qof[13] = aic
    qof[14] = bic

    return qof