import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def save_sorted_plot(y_actual, y_pred, data_name, folder_name, model_name_t, model_name_s, validate=False):
    """
    Generates and saves a line plot comparing actual versus predicted values.
    * The values are sorted by the actual target values to provide a clearer visual 
    representation of the model's fit.
    * Automatically adjusts axis limits to include a 10% padding around the data points.

    Args:
        y_actual (array-like): The actual target values.
        y_pred (array-like): The predicted values generated by the model.
        data_name (str): The name of the dataset (used in the plot title).
        folder_name (str): The directory path where the output plot will be saved.
        model_name_t (str): The formatted model name to be used in the plot title.
        model_name_s (str): The unformatted model name to be used in the saved file name.
        validate (bool): Flag indicating if this is an Out-of-Sample/Validation plot 
                         (True = "80-20 Split", False = "In-Sample"). Defaults to False.
    """
    # --- Data Preparation ---
    # Create a DataFrame with actual and predicted values, then sort by actual values
    df = pd.DataFrame({'Actual': y_actual, 'Predicted': y_pred})
    df_sorted = df.sort_values(by='Actual')
    
    # --- Axis Calculation & Padding ---
    x_end = df_sorted.shape[0]                                   # Total number of observations
    x = np.arange(0, x_end)                                      # X-axis index values
    
    y_start = min(df_sorted['Actual'].min(), df_sorted['Predicted'].min())
    y_end = max(df_sorted['Actual'].max(), df_sorted['Predicted'].max())
    y_dist = y_end - y_start
    
    # Add 10% padding to the Y-axis for better visibility
    y_start = y_start - 0.1 * y_dist
    y_end = y_end + 0.1 * y_dist
    
    # Add 10% padding to the X-axis bounds
    x_end_2 = int(1.1 * x_end) if x_end > 0 else int(0.9 * x_end)
    x_start = int(-0.1 * x_end)

    # --- Plot Generation ---
    plt.figure(figsize=(10, 6))
    plt.plot(x, df_sorted['Predicted'], label='Predicted Values', color='red')
    plt.plot(x, df_sorted['Actual'], color='black', label='Actual Values')
    
    # Configure plot metadata and styling
    split_type = "80-20 Split" if validate else "In-Sample"
    plt.title(f'{data_name} {model_name_t}, {split_type}: yy black/actual vs. yp red/predicted')
    plt.legend()
    plt.ylim(y_start, y_end)
    plt.xlim(x_start, x_end_2)
    
    # Save the figure to the designated folder and clear the plot from memory
    file_suffix = "80_20" if validate else "In_Sample"
    plt.savefig(f'{folder_name}/Statsmodels_{model_name_s}_{file_suffix}.png')
    plt.close('all')


def save_rsq_plot(key, x, r_sq, adj_r_sq, smape, r_sq_cv, method, data_name, folder_name, model_name_t, model_name_s):
    """
    Generates and saves a plot tracking model performance metrics during feature selection.
    * Visualizes R-squared, Adjusted R-squared, sMAPE, and Cross-Validation R-squared
    as the number of selected features increases or decreases.

    Args:
        key (str): The specific identifier for the plot (e.g., "Forward", "Backward").
        x (array-like): The sequence of feature counts (X-axis).
        r_sq (array-like): The standard R-squared metric progression.
        adj_r_sq (array-like): The Adjusted R-squared metric progression.
        smape (array-like): The Symmetric Mean Absolute Percentage Error progression.
        r_sq_cv (array-like): The Cross-Validation R-squared metric progression.
        method (str): The feature selection method used (e.g., "Forward Selection").
        data_name (str): The name of the dataset.
        folder_name (str): The directory path where the output plot will be saved.
        model_name_t (str): The formatted model name to be used in the plot title.
        model_name_s (str): The unformatted model name to be used in the saved file name.
    """
    # --- Plot Generation ---
    plt.figure(figsize=(10, 6))
    plt.plot(x, r_sq, label='R^2', color='red')
    plt.plot(x, adj_r_sq, label='R^2 bar', color='green')
    plt.plot(x, smape, label='sMAPE', color='blue')
    plt.plot(x, r_sq_cv, label='R^2 CV', color='black')
    
    # Configure plot metadata and styling
    plt.title(f'R^2 vs n for {model_name_t} {method} on {data_name}')
    plt.legend()
    
    # Save the figure to the designated folder and clear the plot from memory
    # Note: Kept 'rSq' in the filename here to maintain compatibility if other scripts expect that specific file format
    plt.savefig(f'{folder_name}/Statsmodels_{model_name_s}_rSq_{key}.png')
    plt.close('all')


def save_aic_bic_plot(key, x, aic, bic, method, data_name, folder_name, model_name_t, model_name_s):
    """
    Generates and saves a plot tracking AIC and BIC metrics during feature selection.
    * Visualizes the Akaike Information Criterion (AIC) and Bayesian Information 
    Criterion (BIC) as the number of selected features changes.

    Args:
        key (str): The specific identifier for the plot (e.g., "Forward", "Backward").
        x (array-like): The sequence of feature counts (X-axis).
        aic (array-like): The Akaike Information Criterion progression.
        bic (array-like): The Bayesian Information Criterion progression.
        method (str): The feature selection method used (e.g., "Forward Selection").
        data_name (str): The name of the dataset.
        folder_name (str): The directory path where the output plot will be saved.
        model_name_t (str): The formatted model name to be used in the plot title.
        model_name_s (str): The unformatted model name to be used in the saved file name.
    """
    # --- Plot Generation ---
    plt.figure(figsize=(10, 6))
    plt.plot(x, aic, label='AIC', color='red')
    plt.plot(x, bic, label='BIC', color='green')
    
    # Configure plot metadata and styling
    plt.title(f'AIC/BIC vs n for {model_name_t} {method} on {data_name}')
    plt.legend()
    
    # Save the figure to the designated folder and clear the plot from memory
    plt.savefig(f'{folder_name}/Statsmodels_{model_name_s}_AIC_BIC_{key}.png')
    plt.close('all')